name: mockend CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build mockend
        run: cd mockend && mvn clean package
      - name: Build mockend-st
        run: cd mockend-st && mvn clean package
      - name: Start mockend
        run: cd mockend && java -jar target/mockend-runner.jar
