name: system tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'
      - name: Build mockend
        run: cd mockend && mvn clean package -DskipTests
      - name: Unit Tests
        run: cd mockend && mvn package
      - name: Start mockend
        run: cd mockend && java -jar target/mockend-runner.jar &
      - name: Build mockend-st
        run: cd mockend-st && mvn clean package
      - name: Build mockend-st
        run: cd mockend-st && mvn clean package
      - name: System Tests
        run: cd mockend-st && mvn test-compile failsafe:integration-test failsafe:verify
